// This file is generated by Slice Machine. Update with care!

import ContactForm from './ContactForm';
import Hero from './Hero';
import Image from './Image';
import PartnerLogos from './PartnerLogos';
import Team from './Team';
import TextWithFeatures from './TextWithFeatures';
import TextWithImage from './TextWithImage';

export {
	ContactForm,
	Hero,
	Image,
	PartnerLogos,
	Team,
	TextWithFeatures,
	TextWithImage,
};

export const components = {
	contact_form: ContactForm,
	hero: Hero,
	image: Image,
	partner_logos: PartnerLogos,
	team: Team,
	text_with_features: TextWithFeatures,
	text_with_image: TextWithImage,
};
